pkg_add changes

diff --git a/pkg_add b/pkg_add
--- a/pkg_add
+++ b/pkg_add
@@ -6,7 +6,13 @@ cd ~/misc
 
 for v in "$@"
 do
-	printf '%s\n' "$v" >> fedora-packages.txt
+	if dnf repoquery --qf '%{name}' 2>/dev/null | grep -q '^'"$v"'$'
+	then
+		printf '%s\n' "$v" >> fedora-packages.txt
+	else
+		printf 'Package not found\n' >&2;
+		exit 1
+	fi
 done
 
 xargs sudo dnf install < fedora-packages.txt
